import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Header from '../components/Header';
import Loader from '../components/Loader';
import MainContent from '../components/MainContent';
import { useGlobalContext } from '../components/utils/context';
import { mansorimage } from '../data';
export default function Home() {
  const { isLoading } = useGlobalContext();
  return (
    <div>
      <Head>
        <title>Pinterest</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='relative'>
        {/* header */}
        <Header />
        {isLoading && <Loader />}
        {/* main content */}
        <MainContent />
      </main>
    </div>
  );
}
