import Head from 'next/head';
import Alert from '../components/Alert';
import Header from '../components/Header';
import Loader from '../components/Loader';
import { useEffect } from 'react';
import MainContent from '../components/MainContent';
import { useGlobalContext } from '../components/utils/context';

export default function Home() {
  const { isLoading, MyAlert, setMyAlert } = useGlobalContext();
  useEffect(() => {
    const time = setTimeout(() => {
      setMyAlert(false);
    }, 2000);

    return () => {
      clearTimeout(time);
    };
  }, [MyAlert]);

  return (
    <div>
      <Head>
        <title>Pinterest</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='relative'>
        {/* header */}
        <Header />
        {MyAlert && <Alert msg='please provide a value' />}

        {/* main content */}
        {isLoading ? <Loader /> : <MainContent />}
      </main>
    </div>
  );
}
